version: 2
sphinx:
  configuration: docs/source/conf.py
build:
    os: ubuntu-20.04
    tools:
        python: "3.10"
python:
  version: "3.10"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
