version: 2
sphinx:
  configuration: docs/source/conf.py
build:
  tools:
    python: "3.10"
python:
  version: "3.10"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
